### ISSUE TITLE
There are missing Sodium Predefined Constants for XCHACHA20

### ISSUE THREAD

**Issue by rafalswierczek** [php/doc-en#2802] opened 2023-09-27 03:28 UTC
There are missing Sodium Predefined Constants for XCHACHA20

https://www.php.net/manual/en/sodium.constants.php

```
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_KEYBYTES
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NSECBYTES
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES
SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_ABYTES
```

**Comment by Girgias** [comment] 2023-09-27 19:32
Duplicate of #2747

**Closed by Girgias** 2023-09-27 19:32 UTC
