### ISSUE TITLE
Iterators are supposed to be rewound before usage

### ISSUE THREAD

**Issue by mvorisek** [php/doc-en#1342] opened 2022-01-16 20:32 UTC
### Description

The following code:

```php
<?php

$data = [];
$data['x'] = ['x_v'];
$data['y'] = ['y_v'];

$gen = new \ArrayIterator($data);

var_dump($gen->valid());
var_dump($gen->current());

$filterFx = function ($row) {
    return count($row) !== false; // always true
};
$genOrig = $gen;
$gen = new \CallbackFilterIterator($gen, $filterFx);

$genOrig->next(); // has correctly no effect
// $gen->rewind(); // must be called, iterator is not initialized by default

var_dump($gen->valid());
var_dump($gen->current());
var_dump($gen->valid());
var_dump($gen->next());
```

Resulted in this output:
```
bool(true)
array(1) {
  [0]=>
  string(3) "x_v"
}
bool(false)
NULL
bool(false)
NULL
```

demo https://3v4l.org/trdBX

But I expected this output instead:
```
bool(true)
array(1) {
  [0]=>
  string(3) "x_v"
}
bool(true)
array(1) {
  [0]=>
  string(3) "x_v"
}
bool(true)
NULL
```

### PHP Version

8.0

### Operating System

any

**Comment by Girgias** [comment] 2023-07-25 16:19
Somewhat duplicate of #1300

**Closed by Girgias** 2023-07-25 16:19 UTC
