### ISSUE TITLE
Nonbreaking spaces in examples

### ISSUE THREAD

**Issue by ks74** [php/doc-en#2116] opened 2022-12-24 12:39 UTC
From manual page: https://php.net/language.enumerations.basics
---

For example, this:
enum Suit
{
    case Hearts;
    case Diamonds;
    case Clubs;
    case Spades;
}

has nonbreaking spaces after every "case". If this code is copied into a php-script, it becomes incorrect because nbsp is not a space character. So, this code cannot be executed. 
Of course, it is related to all the documentation, not just the Enumeration part.

**Comment by Girgias** [comment] 2022-12-24 12:44
Duplicate of https://github.com/php/phd/issues/71

**Closed by Girgias** 2022-12-24 12:44 UTC
