### ISSUE TITLE
Weird `<0xa0>` copy paste behavior when copying example code from php docs via firefox > sublimetext4

### ISSUE THREAD

**Issue by jadeops** [php/doc-en#2100] opened 2022-12-21 03:39 UTC
Xubuntu 22.04. Only happens on firefox 108.0.1

https://www.php.net/match

![Peek 2022-12-21 08-58](https://user-images.githubusercontent.com/85561678/208815773-ea19991d-5e7c-41b8-870f-e302fc46f36b.gif)

I searched the php docs for `<0xa0>`. Found it in https://github.com/php/doc-en/blob/master/reference/intl/messageformatter/format-message.xml#L124-L125 Maybe added in commit: https://github.com/php/doc-en/commit/bbafea6c3de3dca08f2833b153fd6dbc772e7744

Is this a php docs bug/firefox bug/sublime text4 bug?

**Comment by cmb69** [comment] 2022-12-21 09:47
This is actually a duplicate of https://github.com/php/phd/issues/71.

**Closed by cmb69** 2022-12-21 09:47 UTC
