### ISSUE TITLE
List of Resource Types table wider than content block

### ISSUE THREAD

**Issue by simbirsky** [php/doc-en#2356] opened 2023-03-16 07:31 UTC
From manual page: https://php.net/resource

---

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/9012194/225545777-b33c5324-607b-4b90-a091-f88c3f8a8e0a.png">

I use firefox 110.0.1 (64-bit) on macos.

**Comment by Girgias** [comment] 2023-03-17 21:56
Duplicate of #792

**Closed by Girgias** 2023-03-17 21:56 UTC
Labels: duplicate
