### ISSUE TITLE
Loose comparison table doesn't match PHP 8+

### ISSUE THREAD

**Issue by direc85** [php/doc-en#1214] opened 2021-12-17 13:06 UTC
From manual page: https://php.net/types.comparisons

The loose comparison chart doesn't match PHP 8:

PHP 7.4:
var_dump("php" == 0);
bool(true)

PHP 8.0:
var_dump("php" == 0);
bool(false)

This reads in PHP 8 release notes, but the documentation should also be updated.

Thanks!

**Comment by cmb69** [comment] 2021-12-17 13:15
Thanks! Looks like this is a duplicate of #1146.

**Closed by cmb69** 2021-12-17 13:15 UTC

**Comment by cmb69** [comment] 2021-12-17 13:29
Well, not exactly a duplicate of the other issue, but all changes need to be addressed anyway.
