### ISSUE TITLE
Functions ssh2_sftp : wrong character in the example

### ISSUE THREAD

**Issue by BeWog** [php/doc-en#2085] opened 2022-12-15 13:02 UTC
Hi,

In the 1st example ("Example #1 Opening a file via SFTP") of this page : https://www.php.net/manual/fr/function.ssh2-sftp.php
I copy/paste the example code for a test.

Via PHP CLI, i have this error:
```
PHP Fatal error:  Uncaught Error: Call to undefined function  ssh2_connect() in
```

Then (after a long time and became crazy), i launch via Apache PHP:
```
PHP Fatal error:  Uncaught Error: Call to undefined function \xc2\xa0ssh2_connect() in
```
"\xc2\xa0" ? 😲
There is a wrong character in the doc.

I deleted this and it works !

**Comment by cmb69** [comment] 2022-12-15 13:09
This is a duplicate of https://github.com/php/phd/issues/71.

**Closed by cmb69** 2022-12-15 13:09 UTC
