### ISSUE TITLE
Link to ICU Locale Explorer results in HTTP Not Found

### ISSUE THREAD

**Issue by dsuurlant** [php/doc-en#993] opened 2021-10-04 12:42 UTC
From manual page: https://php.net/intl.configuration

---

> intl.default_locale string
The locale that will be used in intl functions when none is specified (either by omitting the corresponding argument or by passing NULL). These are ICU locales, not system locales. The built-in ICU locales and their data can be explored at » http://demo.icu-project.org/icu-bin/locexp.

The above link results in a 404.

Alternative link with locales info, but unknown for how long this stays up: [https://www.localeplanet.com/icu/index.html](https://www.localeplanet.com/icu/index.html).

**Comment by cmb69** [comment] 2021-10-04 12:54
That should be fixed upstream; on https://icu4c-demos.unicode.org/icu-bin/icudemos there is a link pointing to that very page.

**Comment by nikic** [comment] 2021-11-12 10:45
Duplicate of #669.

**Closed by nikic** 2021-11-12 10:45 UTC
