### ISSUE TITLE
Broken layout

### ISSUE THREAD

**Issue by carlos-landeira** [php/doc-en#1928] opened 2022-11-01 19:13 UTC
From manual page: https://php.net/resource

![image](https://user-images.githubusercontent.com/70922382/199318562-5cc29b9f-7ea6-445b-90d6-6adfab4f8b47.png)

**Comment by cmb69** [comment] 2022-11-01 19:17
Duplicate of #792.

**Closed by cmb69** 2022-11-01 19:17 UTC
