### ISSUE TITLE
Vote Up or Down Not Working

### ISSUE THREAD

**Issue by nevilmakadia** [php/doc-en#1487] opened 2022-03-29 04:57 UTC
From manual page: https://php.net/debugger

---

**Comment by cmb69** [comment] 2022-03-29 08:42
Presuming that you're using IPv6, this is a duplicate of https://bugs.php.net/bug.php?id=76961. But anyhow, this is not a documentation issue.

**Closed by cmb69** 2022-03-29 08:42 UTC
