### ISSUE TITLE
Broken link on intl.configuration

### ISSUE THREAD

**Issue by patagu** [php/doc-en#1088] opened 2021-11-12 10:42 UTC
From manual page: https://php.net/intl.configuration

---
The link to the built-in ICU locales and their data on the intl.default_locale configuration section is broken: [http://demo.icu-project.org/icu-bin/locexp](http://demo.icu-project.org/icu-bin/locexp)

**Comment by nikic** [comment] 2021-11-12 10:45
Duplicate of #669.

**Closed by nikic** 2021-11-12 10:45 UTC
